import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'daily_dao.dart';
import 'daily_entries_table.dart';

part 'database.g.dart';

@DriftDatabase(tables: [DailyEntries], daos: [DailyDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Test-only: run against an in-memory executor instead of the on-device
  /// file (path_provider is unavailable in `flutter test`).
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
        onCreate: (m) => m.createAll(),
        onUpgrade: (m, from, to) async {
          if (from < 2) {
            // 1. Add the new nullable catalog columns.
            await m.addColumn(dailyEntries, dailyEntries.moodRating);
            await m.addColumn(dailyEntries, dailyEntries.energyRating);
            await m.addColumn(dailyEntries, dailyEntries.nutritionRating);
            await m.addColumn(dailyEntries, dailyEntries.physicalRating);
            await m.addColumn(dailyEntries, dailyEntries.socialRating);
            await m.addColumn(dailyEntries, dailyEntries.productivityRating);
            await m.addColumn(dailyEntries, dailyEntries.waterRating);
            await m.addColumn(dailyEntries, dailyEntries.caffeineRating);
            await m.addColumn(dailyEntries, dailyEntries.alcoholRating);
            await m.addColumn(dailyEntries, dailyEntries.smokingRating);
            await m.addColumn(dailyEntries, dailyEntries.medicationTaken);
            await m.addColumn(dailyEntries, dailyEntries.workdayFlag);

            // 2. Relax NOT NULL on the original four. TableMigration rebuilds
            //    the table to match the Dart schema (now .nullable()), keeping
            //    existing rows/values.
            await m.alterTable(TableMigration(dailyEntries));
          }
        },
      );

  // `dailyDao` is generated by drift (database.g.dart); callers use db.dailyDao.

  static QueryExecutor _openConnection() {
    return LazyDatabase(() async {
      final dir = await getApplicationDocumentsDirectory();
      return NativeDatabase.createInBackground(
        File(p.join(dir.path, 'daily_wellness.sqlite')),
      );
    });
  }
}
