import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'daily_dao.dart';
import 'daily_entries_table.dart';

part 'database.g.dart';

@DriftDatabase(tables: [DailyEntries], daos: [DailyDao])
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  /// Test-only: run against an in-memory executor instead of the on-device
  /// file (path_provider is unavailable in `flutter test`).
  AppDatabase.forTesting(super.executor);

  @override
  int get schemaVersion => 1;

  // `dailyDao` is generated by drift (database.g.dart); callers use db.dailyDao.

  static QueryExecutor _openConnection() {
    return LazyDatabase(() async {
      final dir = await getApplicationDocumentsDirectory();
      return NativeDatabase.createInBackground(
        File(p.join(dir.path, 'daily_wellness.sqlite')),
      );
    });
  }
}
